#!/bin/bash

for f in "$@"
do
    echo -n "$f "
    duration=$(oggz info "$f" | grep Duration)
    h=$(echo $duration | awk -F: '{print $2}')
    m=$(echo $duration | awk -F: '{print $3}')
    s=$(echo $duration | awk -F: '{print $4}')

    shopt -s extglob     # Turn on extended globbing.
    h=${h##+([ 0])}         # strip longest matching series of 0's.
    m=${m##+([ 0])}
    shopt -u extglob     # Turn off extended globbing.

    if [[ -n $h ]]; then
	h="${h}h"
    fi
    if [ ${s%.*} -gt 20 ]; then
       let "m=m+1"
    fi
    newname="${f%.*}-${h}${m}m.${f##*.}"
    echo '->' $newname
    mv "$f" "$newname"
done
