#!/bin/bash

gst_softsub () {
    ext=${2##*.}
    case $ext in
	"mkv")
	    gstdemux=matroskademux
	    ;;
	*)
	    echo "This script does not support $ext files with gstreamer"
	    return
	    ;;
    esac
    gst-launch-1.0 -q filesrc location="$2" ! $gstdemux ! $1 ! kateenc category=spu-subtitles ! oggmux ! filesink location="$3"
}

if [ $# = 0 ]; then
    echo 'Usage: transcode_ch7 [options] files...'
    echo 'Options: [--keepaudio|--dualaudio|--dualreverse][--hardsrt[=#]|--hardass[=#]][--sub=#][--softdvdsub|--softass][--externalsrt][--outdir=<path>]'
    exit
fi

args=$(getopt -o '' -l keepaudio,dualaudio,dualreverse,hardsrt::,hardass::,sub:,softdvdsub,softass,externalsrt,outdir: -- "$@")

#defaults
vrate="640k"
audioopts="-c:a libvorbis -b:a 128k"
mapopts=""
filteropts=()
subnum=0
outdir=.

eval set -- ${args%%-- *}
# Processing options
for a in "$@"
do
    case $a in
	"--keepaudio")
	    audioopts="-c:a copy"
	    ;;
	"--dualaudio")
	    vrate="512k"
	    mapopts="-map 0:v -map 0:a"
	    bEncodeKate=1
	    ;;
	"--dualreverse")
	    vrate="512k"
	    mapopts="-map 0:v -map 0:a:1 -map 0:a:0"
	    bEncodeKate=1
	    ;;
	"--hardsrt")
	    OverlaySRT=0
	    option=OverlaySRT
	    ;;
	"--hardass")
	    OverlayASS=0
	    option=OverlayASS
	    ;;
	"--sub")
	    option=subnum
	    ;;
	"--externalsrt")
	    bExtSRT=1
	    ;;
	"--softdvdsub")
	    bDVDsub=1
	    ;;
	"--softass")
	    bSoftASS=1
	    ;;
	"--outdir")
	    option=outdir
	    ;;
	*)
	    if [ $option ]; then
		if [ -n "$a" ]; then
		    eval ${option}=${a}
		fi
		unset option
	    else
		echo Unsupported option: $a
	    fi
	    ;;
    esac
done

eval set -- ${args##*-- }
# Transcoding files
for f in "$@"
do
    fname=${f##*/}         # remove path
    fname=${fname%.*}      # remove extension
    vidname=${fname// /_}  # replace spaces
    final=${outdir}/${vidname}.ogv

    fdir=${f%/*}

    srtfile=${outdir}/${vidname}.srt
    ssafile=${outdir}/${vidname}.ssa
    subfile=${outdir}/${vidname}.kate
    avfile=${outdir}/${vidname}.ogg
    output=$final

    echo "Transcoding $f to $final"

    if [ $bExtSRT ]; then
	srtfile="${fdir}/${fname}.srt"
    fi

    if [ $bEncodeKate ]; then
	if [ $bDVDsub ]; then
	    gst_softsub dvdsubparse "$f" "$subfile"
	elif [ $bSoftASS ]; then
	    gst_softsub ssaparse "$f" "$subfile"
	else
	    if [ ! $bExtSRT ]; then
		ffmpeg -i "$f" -map 0:s:${subnum} -c:s srt -v error "$srtfile"
	    fi
	    kateenc -t srt -c SUB -l en -M -o "$subfile" "$srtfile"
	fi
	output=$avfile
    fi

    if [ $OverlaySRT ]; then
	if [ ! $bExtSRT ]; then	
	    ffmpeg -i "$f" -map 0:s:${OverlaySRT} -c:s copy -v error "$srtfile"
	fi
	filteropts=("-vf" "subtitles=${srtfile}")
    fi
    if [ $OverlayASS ]; then
	ffmpeg -i "$f" -map 0:s:${OverlayASS} -c:s copy -v error "$ssafile"
	filteropts=("-vf" "ass=${ssafile}")
    fi
    i=0
    for o in "${filteropts[@]}"
    do
	filteropts[$i]=$(printf '%q' "$o")
	let i+=1
    done

    ffmpeg -i "$f" "${filteropts[@]}" -c:v libtheora -b:v ${vrate} -an -sn -pass 1 -passlogfile "$vidname" -f rawvideo -v error -y /dev/null
    ffmpeg -i "$f" ${mapopts} "${filteropts[@]}" -c:v libtheora -b:v ${vrate} ${audioopts} -pass 2 -passlogfile "$vidname" -metadata title="$fname" -v error "$output"
    rm "${vidname}"*.log

    if [ $bEncodeKate ]; then
	oggz merge -o "$final" "$avfile" "$subfile"
	rm "$subfile" "$avfile"
    fi
    if [[ -f "$srtfile" && ! $bExtSRT ]]; then
	rm "$srtfile"
    fi
    if [ $OverlayASS ]; then
	rm "$ssafile"
    fi
done
