#!/bin/bash

echo_args () { #for testing
    for a in "$@"; do
	echo $a
    done
}

append_filter () {
    if [ -z "$filteropts" ]; then
	filteropts[0]="-vf"
    else
	filteropts[1]+=","
    fi
    filteropts[1]+=$(printf "%q" "$1")
}

gst_softsub () {
    ext=${2##*.}
    case $ext in
	"mkv")
	    gstdemux=matroskademux
	    ;;
	*)
	    echo "This script does not support $ext files with gstreamer"
	    return
	    ;;
    esac
    gst-launch-1.0 -q filesrc location="$2" ! $gstdemux ! $1 ! kateenc category=spu-subtitles ! oggmux ! filesink location="$3"
}

if [ $# = 0 ]; then
    echo 'Usage: transcode_ch7 [options] files...'
    echo 'Options: [--dualaudio|--dualreverse|--keepaudio|--keeprevaudio][--hardsrt[=#]|--hardass[=#]][--sub=#][--softdvdsub|--softass][--externalsrt][--outdir=<path>][--scale]'
    exit
fi

args=$(getopt -o '' -l dualaudio,dualreverse,keepaudio,keeprevaudio,hardsrt::,hardass::,sub:,softdvdsub,softass,externalsrt,outdir:,scale -- "$@")
if [ $? -ne 0 ]; then
    exit
fi

#defaults
vrate="640k"
audioopts="-c:a libvorbis -b:a 128k"
subnum=0
outdir=.
loglvl=error
nicer=nice

eval set -- ${args%%-- *}
# Processing options
for a in "$@"
do
    case $a in
	"--dualaudio")
	    vrate="512k"
	    mapopts="-map 0:a -map 0:v"
	    bEncodeKate=1
	    ;;
	"--dualreverse")
	    vrate="512k"
	    mapopts="-map 0:a:1 -map 0:a:0 -map 0:v"
	    bEncodeKate=1
	    ;;
	"--keepaudio")
	    audioopts="-c:a copy"
	    mapopts="-map 0:a -map 0:v"
	    ;;
	"--keeprevaudio")
	    audioopts="-c:a copy"
	    mapopts="-map 0:a:1 -map 0:a:0 -map 0:v"
	    bEncodeKate=1
	    ;;
	"--hardsrt")
	    OverlaySRT=0
	    option=OverlaySRT
	    ;;
	"--hardass")
	    OverlayASS=0
	    option=OverlayASS
	    ;;
	"--sub")
	    bEncodeKate=1
	    bSub=1
	    option=subnum
	    ;;
	"--externalsrt")
	    bExtSRT=1
	    ;;
	"--softdvdsub")
	    bDVDsub=1
	    ;;
	"--softass")
	    bSoftASS=1
	    ;;
	"--outdir")
	    option=outdir
	    ;;
	"--scale")
	    scaleH=480
	    ;;
	*)
	    if [ $option ]; then
		if [ -n "$a" ]; then
		    eval ${option}=${a}
		fi
		unset option
	    else
		echo Unsupported option: $a
		exit
	    fi
	    ;;
    esac
done

eval set -- ${args##*-- }
# Transcoding files
for f in "$@"
do
    fname=${f##*/}         # remove path
    fname=${fname%.*}      # remove extension
    vidname=${fname// /_}  # replace spaces
    final=${outdir}/${vidname}.ogv

    fdir=$(dirname "$f")

    srtfile=${outdir}/${vidname}.srt
    ssafile=${outdir}/${vidname}.ssa
    subfile=${outdir}/${vidname}.kate
    avfile=${outdir}/${vidname}.ogg
    output=$final

    filteropts=()

    echo "Transcoding $f to $final"

    if [ $bExtSRT ]; then
	cp "${fdir}/${fname}.srt" "$srtfile"
    fi

    if [ $scaleH ]; then
	append_filter "scale=-1:${scaleH}"
    fi
    
    if [ $bEncodeKate ]; then
	if [ $bDVDsub ]; then
	    DVDsubSrc="$f"
	    if [ $bSub ]; then
		DVDsubSrc=${outdir}/${vidname}.1sub.mkv
		ffmpeg -i "$f" -map 0:v -map 0:s:${subnum} -c:v copy -c:s dvdsub -v $loglvl ${DVDsubSrc};
	    fi
	    gst_softsub dvdsubparse "${DVDsubSrc}" "$subfile"
	    if [ $bSub ]; then rm ${DVDsubSrc}; fi
	    DVDsubSrc=
	elif [ $bSoftASS ]; then
	    gst_softsub ssaparse "$f" "$subfile"
	else
	    if [ ! $bExtSRT ]; then
		ffmpeg -i "$f" -map 0:s:${subnum} -c:s srt -v $loglvl "$srtfile"
	    fi
	    kateenc -t srt -c SUB -l en -M -o "$subfile" "$srtfile"
	fi
	output=$avfile
    fi

    if [ $OverlaySRT ]; then
	if [ ! $bExtSRT ]; then	
	    ffmpeg -i "$f" -map 0:s:${OverlaySRT} -c:s copy -v $loglvl -y "$srtfile"
	fi
	append_filter "subtitles=${srtfile}"
    fi
    if [ $OverlayASS ]; then
	ffmpeg -i "$f" -map 0:s:${OverlayASS} -c:s copy -v $loglvl "$ssafile"
	append_filter "ass=${ssafile}"
    fi

    ${nicer} ffmpeg -i "$f" ${mapopts} ${filteropts[@]} -c:v libtheora -b:v ${vrate} -c:a copy -sn -pass 1 -passlogfile "${outdir}/$vidname" -f rawvideo -v $loglvl -y /dev/null
    ${nicer} ffmpeg -i "$f" ${mapopts} ${filteropts[@]} -c:v libtheora -b:v ${vrate} ${audioopts} -pass 2 -passlogfile "${outdir}/$vidname" -metadata:s:v title="$fname" -metadata:s:a title= -v $loglvl "$output"
    rm "${outdir}/${vidname}"*.log

    if [ $bEncodeKate ]; then
	oggz merge -o "$final" "$avfile" "$subfile"
	rm "$subfile" "$avfile"
    fi
    if [[ -f "$srtfile" ]]; then
	rm "$srtfile"
    fi
    if [ $OverlayASS ]; then
	rm "$ssafile"
    fi
done
